from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import font_manager as fm


ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = ROOT / "figures"
CN_FONT_PATH = Path("/mnt/c/Windows/Fonts/simsun.ttc")
EN_FONT_PATH = Path("/mnt/c/Windows/Fonts/times.ttf")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Draw board-vs-local probability difference figures.")
    parser.add_argument(
        "--comparison-csv",
        default="deploy/board_probabilities_comparison.csv",
        help="Detailed comparison CSV generated by deploy/compare_board_probabilities.py",
    )
    parser.add_argument(
        "--summary-json",
        default="deploy/board_probabilities_comparison_summary.json",
        help="Summary JSON generated by deploy/compare_board_probabilities.py",
    )
    return parser.parse_args()


def register_font(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Missing font: {path}")
    fm.fontManager.addfont(str(path))
    return fm.FontProperties(fname=str(path)).get_name()


def setup_rcparams() -> tuple[fm.FontProperties, fm.FontProperties]:
    cn_font_name = register_font(CN_FONT_PATH)
    en_font_name = register_font(EN_FONT_PATH)

    plt.rcParams["figure.dpi"] = 150
    plt.rcParams["savefig.dpi"] = 300
    plt.rcParams["axes.unicode_minus"] = False
    plt.rcParams["font.family"] = cn_font_name
    plt.rcParams["font.size"] = 10.5
    plt.rcParams["axes.linewidth"] = 0.8
    plt.rcParams["xtick.direction"] = "out"
    plt.rcParams["ytick.direction"] = "out"
    plt.rcParams["mathtext.fontset"] = "dejavuserif"

    cn_fp = fm.FontProperties(family=cn_font_name, size=10.5)
    en_fp = fm.FontProperties(family=en_font_name, size=10.5)
    return cn_fp, en_fp


def load_comparison_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def style_axis(ax) -> None:
    ax.grid(color="#d9d9d9", linewidth=0.6, alpha=0.8)
    for spine in ax.spines.values():
        spine.set_linewidth(0.8)
        spine.set_color("black")


def main() -> None:
    args = parse_args()
    comparison_csv_path = Path(args.comparison_csv)
    summary_json_path = Path(args.summary_json)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    cn_fp, en_fp = setup_rcparams()
    rows = load_comparison_rows(comparison_csv_path)
    _ = summary_json_path
    classes = [0, 2, 4]
    colors = {0: "#4c78a8", 2: "#f58518", 4: "#54a24b"}

    fig, axes = plt.subplots(1, 2, figsize=(8.1, 3.5))

    for label in classes:
        board_prob = np.asarray([float(row[f"board_prob_{label}"]) for row in rows], dtype=np.float64)
        local_prob = np.asarray([float(row[f"local_prob_{label}"]) for row in rows], dtype=np.float64)
        delta_prob = np.asarray([float(row[f"delta_prob_{label}"]) for row in rows], dtype=np.float64)

        axes[0].scatter(
            board_prob,
            local_prob,
            s=18,
            alpha=0.70,
            color=colors[label],
            edgecolors="none",
            label=f"{label} ml",
        )
        axes[1].scatter(
            board_prob,
            delta_prob,
            s=18,
            alpha=0.70,
            color=colors[label],
            edgecolors="none",
            label=f"{label} ml",
        )

    axes[0].plot([0.0, 1.0], [0.0, 1.0], linestyle="--", linewidth=0.9, color="#666666")
    axes[0].set_title("主板与本地概率散点对比", fontproperties=cn_fp, pad=6)
    axes[0].set_xlabel("主板概率 p_board", fontproperties=cn_fp, labelpad=4)
    axes[0].set_ylabel("本地概率 p_local", fontproperties=cn_fp, labelpad=6)
    axes[0].set_xlim(-0.02, 1.02)
    axes[0].set_ylim(-0.02, 1.02)
    style_axis(axes[0])

    axes[1].axhline(0.0, linestyle="--", linewidth=0.9, color="#666666")
    axes[1].set_title("概率差与主板概率关系", fontproperties=cn_fp, pad=6)
    axes[1].set_xlabel("主板概率 p_board", fontproperties=cn_fp, labelpad=4)
    axes[1].set_ylabel("概率差 Δp", fontproperties=cn_fp, labelpad=6)
    axes[1].set_xlim(-0.02, 1.02)
    style_axis(axes[1])

    handles, labels = axes[0].get_legend_handles_labels()
    legend = fig.legend(
        handles,
        labels,
        loc="lower center",
        ncol=3,
        bbox_to_anchor=(0.5, -0.01),
        frameon=False,
        prop=en_fp,
    )
    for text in legend.get_texts():
        text.set_fontproperties(en_fp)

    fig.subplots_adjust(left=0.08, right=0.985, bottom=0.22, top=0.90, wspace=0.25)

    for suffix in (".png", ".svg"):
        fig.savefig(
            OUTPUT_DIR / f"图-主板与本地概率差异散点图{suffix}",
            bbox_inches="tight",
            pad_inches=0.03,
            facecolor="white",
        )
    plt.close(fig)


if __name__ == "__main__":
    main()
